#!/bin/bash
while :
do
	echo "Press [CTRL+C] to stop.."
sleep 60
	xvfb-run -a node perang.js --masukcodenvy $1
	sudo rm -rf /tmp/* /tmp/.*
	echo "bismillah ke c9"
	xvfb-run -a node perang.js --masukc9 $1
done
