var Horseman = require('node-horseman');
var horseman = new Horseman();
horseman.open("https://c9.io/login")
.viewport(1000,1000)
.wait(5000)
.then(function(){console.log("open");})
.catch(function(err){console.log(err);})
.type('#id-username','slafe1@yandex.com')
.wait(5000)
.then(function(){console.log("username");})
.catch(function(err){console.log(err);})
.type('#id-password','plokotoklucu')
.wait(5000)
.then(function(){console.log("password");})
.catch(function(err){console.log(err);})
.keyboardEvent('keypress',16777221)
.wait(5000)
.then(function(){console.log("enter");})
.catch(function(err){console.log(err);})
.wait(5000)
.click("#card-new-project")
.wait(5000)
.then(function(){console.log("new");})
.catch(function(err){console.log(err);})
.type("input[name='name']","sampai2")
.wait(5000)
.then(function(){console.log("name");})
.catch(function(err){console.log(err);})
// .type("input[placeholder='e.g. ajaxorg/ace or git@github.com:ajaxorg/ace.git']","https://github.com/lokimonoton/durant.git")
// .wait(5000)
// .then(function(){console.log("git");})
// .catch(function(err){console.log(err);})
.click("button[type='submit']")
.wait(50000)
.then(function(){console.log("masuk ke ide");})
.catch(function(err){console.log(err);})
.url()
.then(function(data){horseman
.viewport(1000,1000)
.open(data)
.wait(100000)
.screenshot()
})
.catch(function(err){console.log(err);})
.on("error",(msg,trace)=>{
    console.log(msg)
})

