var Horseman = require('node-horseman');
var horseman = new Horseman();
horseman.open("https://c9.io/login")
.wait(5000)
.then(function(){console.log("open");})
.catch(function(err){console.log(err);})
.type('#id-username','slafe1@yandex.com')
.wait(5000)
.then(function(){console.log("username");})
.catch(function(err){console.log(err);})
.type('#id-password','plokotoklucu')
.wait(5000)
.then(function(){console.log("password");})
.catch(function(err){console.log(err);})
.keyboardEvent('keypress',16777221)
.wait(5000)
.then(function(){console.log("enter");})
.catch(function(err){console.log(err);})
.wait(5000)
.click("#card-new-project")
.wait(5000)
.then(function(){console.log("new");})
.catch(function(err){console.log(err);})
.screenshot('panda.png')
.close()